datatrails/datatrails-docs

config/production/config.toml
Added the new pages hosting url
=> Add updated hosting config

content/docs/quickstart/when-who-did-what-to-a-thing/index.md
added new position statement as reviewed by Gartner
=> updated to new position statement

content/docs/user-patterns/_index.md, content/docs/user-patterns/authenticity-and-attestation/index.md, content/docs/user-patterns/bill-of-materials/index.md, content/docs/user-patterns/state-machine/index.md, layouts/blog/list.html, layouts/contributing/list.html, layouts/contributors/list.html, layouts/docs/list.html, layouts/index.html
Needs much improvement with diagrams but we can do that later. Basic section good to go.
=> Add basic User Patterns section

assets/scss/common/_dark.scss, assets/scss/components/_buttons.scss, config/_default/params.toml, layouts/docs/single.html, layouts/partials/sidebar/docs-menu.html
Matches https://github.com/h-enk/doks/pull/243/commits and https://github.com/h-enk/doks/commit/52e33eba69a66f72c676fad08d9f2dbcf2311982
=> Adding Collapsible to match Upstream

content/docs/setup-and-administration/configuring-azure-clients-for-non-interactive-use/index.md, content/docs/setup-and-administration/getting-access-tokens-using-client-secret/index.md, layouts/shortcodes/img.html
Updated Application Registration link changed ../configuring-azure-clients-for-non-interactive-access/  --> ../configuring-azure-clients-for-non-interactive-use/ 
And. . . 
Changed ..registering-your-azure-active-directory-with-rkvst/#finding-your-tenant-id --> ../registering-your-azure-active-directory-with-rkvst/#finding-your-tenant-id)
Changed https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-oauth2-client-creds-grant-flow> --> https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow
Adding modal images. . .
=> Updating Application Registration and How to Locate your Tenant link

layouts/shortcodes/img.html
Noticed that the comment tag wasn't complete thus showing on the site.
=> Adding comment tag

content/docs/setup-and-administration/registering-your-azure-active-directory-with-rkvst/index.md
Changing portal.azure.com --> https://portal.azure.com
=> Updating portal.com link

layouts/shortcodes/imgDark.html
Updated shortcode for dark images and was able to test dark and light class images.
=> Updating app reg tenant link

content/docs/api-reference/assets-api/index.md, content/docs/api-reference/attachments-api/index.md, content/docs/api-reference/blobs-api/index.md, content/docs/api-reference/blockchain-api/index.md, content/docs/api-reference/compliance-api/index.md, content/docs/api-reference/events-api/index.md, content/docs/api-reference/iam-policies-api/index.md, content/docs/api-reference/locations-api/index.md, content/docs/api-reference/microsoft-iothub-api/index.md, content/docs/api-reference/svc-buses-api/index.md, content/docs/api-reference/system-api/index.md, content/docs/api-reference/tenancies-api/index.md, content/docs/api-reference/tls-ca-certificates-api/index.md
Added curl examples from the old Read The Docs to the API Reference, largely should be ported with proper formatting applied and any old Product References to Archivist or similar updated
=> Adding curl examples

content/docs/overview/introduction/index.md
Adding "Integrity" to docs intro page
=> Adding Integrity to docs Introduction

content/docs/user-patterns/_index.md
Fixing one of Rob's comments in https://github.com/jitsuin-inc/rkvst-docs/pull/106#discussion_r688462912
=> Resolving Rob's Comments

config/production/config.toml, static/CNAME
Updating the domain listings for the migration to rkvst.com
Relying on the DNS to be updated before merging
=> Updating Production URLs

README.md, config/_default/menus.toml, config/_default/params.toml, content/_index.md, content/contributing/formatting-content/advanced-formatting/index.md, content/contributing/formatting-content/style-guide/index.md, content/sales/contactus/index.md
=> New website link

content/docs/api-reference/iam-subjects-api/index.md, content/docs/api-reference/locations-api/index.md, content/docs/api-reference/microsoft-iothub-api/index.md, content/docs/api-reference/svc-buses-api/index.md, content/docs/api-reference/system-api/index.md, content/docs/api-reference/tenancies-api/index.md, content/docs/api-reference/tls-ca-certificates-api/index.md
There is an issue in the OpenAPI spec for subjects that means the render doesn't function correctly
This should be fixed in the next release but we may wish to hold back on merging this until that point
=> Adding IAM Docs and correct ordering

layouts/partials/head/script-header.html
Adding Google Analytics to header file
=> Added Google Analytics

config/_default/menus.toml, content/support/contactus/index.md, layouts/partials/header/header.html
Added new support site, added new support email just in case; also point RKVST title back to main rkvst website
=> Fixing top menus

content/contributing/formatting-content/style-guide/index.md, content/docs/api-reference/assets-api/index.md, content/docs/api-reference/attachments-api/index.md, content/docs/api-reference/blobs-api/index.md, content/docs/api-reference/blockchain-api/index.md, content/docs/api-reference/compliance-api/index.md, content/docs/api-reference/events-api/index.md, content/docs/api-reference/iam-policies-api/index.md, content/docs/api-reference/iam-subjects-api/index.md, content/docs/api-reference/locations-api/index.md, content/docs/api-reference/microsoft-iothub-api/index.md, content/docs/api-reference/svc-buses-api/index.md, content/docs/api-reference/system-api/index.md, content/docs/api-reference/tenancies-api/index.md, content/docs/api-reference/tls-ca-certificates-api/index.md
Now we have settled on the name for production I have updated all $URL values to represent this
=> Updated all $URL values to be https://app.rkvst.io

content/docs/quickstart/Tutorial/index.md
Reviewing the tutorial there were some places we had used different persons and tenses, I have gone through and tried to make the content slightly more consistent tonally with the rest of the documentation by using 'You' over 'We' - as a tutorial that is targeted at telling people how to do things as opposed to being more collaborative I think this is the right prioritisation.
Feel free to review as while I think this is complete there may some smaller hiccups in places we need to de-tangle as well as some places for the feedback we have received recently that should be added
Those may need to be handled in more specific smaller PRs though to keep us from relying too heavily on monolithic PRs
=> Making person consistent throughout the tutorial

layouts/partials/footer/footer.html
Want people to know to look at support knowledgebase if Docs don't answer questions - promotes better journey when encountering issues
=> Add footer pointing to Support Knowledgebase

content/docs/quickstart/Tutorial/index.md, package-lock.json
Adding verbiage about sharing filters based on feedback:
https://rkvst.zendesk.com/agent/tickets/10428
=> Sharing update zd10428

content/contributing/getting-started/pulling-and-building-rkvst-docs/index.md, content/docs/overview/core-concepts/index.md, content/docs/quickstart/Tutorial/index.md, content/docs/quickstart/creating-an-asset/index.md, content/docs/quickstart/creating-an-event-against-an-asset/index.md, content/docs/quickstart/grouping-assets-by-location/index.md, content/docs/quickstart/managing-access-to-an-asset-with-abac/index.md, content/docs/quickstart/sharing-assets-with-obac/index.md, content/docs/quickstart/when-who-did-what-to-an-asset/index.md
Minor grammar edits and changes to American English spelling.
=> Minor Grammar Fixes

config/postcss.config.js
Other change that might be needed to enable clipboard
=> Adding buttons scss

assets/js/clipboard.js
https://github.com/leflambeur/rkvst-docs/blob/main/assets/js/clipboard.js
This implementation works
Currently live does not, trying to align them
=> Matching Working Implementation

package.json
This may fix our issues with the clipboard code and how it is being packaged
=> Chainging devDependencies to dependencies

content/docs/api-reference/iam-policies-api/index.md, content/docs/api-reference/invites-api/index.md, content/docs/api-reference/locations-api/index.md, content/docs/api-reference/tenancies-api/index.md, content/docs/api-reference/tls-ca-certificates-api/index.md
Adding docs for new Invites API Endpoint
=> Add Invites API File + Fix Ordering

content/contributing/formatting-content/style-guide/index.md, content/docs/api-reference/iam-policies-api/index.md
Maintenance and Firmware behaviours are deprecated - this is a cleanup on any errant and left over references
=> Removed all Maintenance and Firmware behaviours

content/docs/quickstart/creating-an-asset/index.md
Added JSON/curl command option to the step-by-step tabs.
=> Creating an Asset JSON Tabs

content/docs/quickstart/creating-an-event-against-an-asset/index.md
Added JSON/curl command option to the step-by-step tabs.
=> Creating an Event Against an Asset JSON Tabs

content/docs/quickstart/grouping-assets-by-location/index.md, content/docs/quickstart/managing-access-to-an-asset-with-abac/index.md, content/docs/quickstart/sharing-assets-with-obac/index.md
Added JSON tabs to Location, ABAC, and OBAC sections.
=> Adding JSON Tabs to RKVST Basics

layouts/shortcodes/openapi.html
Changing openapi renderer with @j-hartley's proposed fix
=> Testing proposed renderer fix

assets/scss/app.scss, assets/scss/common/_dark.scss, assets/scss/components/_accordion.scss, assets/scss/components/_code.scss
Recent upgrade to Bootstrap broke styling for Accordion Items - have supplemented custom CSS overrides
=> Fixed Accordions Icons and Styling

content/docs/rkvst-basics/grouping-assets-by-location/index.md
Added YAML and JSON options to view locations.
=> Adding YAML Locations_List and API GET Location Options

content/docs/beyond-the-basics/compliance-policies/index.md
Verified domain section not publishing properly, this is a potential fix to that issue. There were previously overlapping table of contents positions.
=> fix to beyond the basics toc order

content/docs/api-reference/blockchain-api/index.md
Blockchain endpoint version updated from alpha1 to alpha2, swagger pointer updated
=> Update to alpha2

config/_default/config.toml
Added security headers to docs.rkvst.com. CSP temporarily set to report only.
=> Add headers to docs.rkvst.com

content/docs/overview/advanced-concepts/index.md
Section on Simple Hash and Khipu added to the advanced concepts.
=> Proof Mechanisms advanced concepts section

content/docs/api-reference/assets-api/index.md
Includes examples for fetching assets by proof mechanism and fetching events ordered for the SIMPLEHASHv1 schema.
=> Fetch Assets by Proof Mechanism (API Reference)

config/_default/config.toml, layouts/partials/head/head.html
The <meta> tag route works, so added all other security headers there too. 
Also added missed Google Analytics script to CSP.
=> Add google analytics script to CSP and add other security headers

content/docs/rkvst-basics/creating-an-asset/index.md, content/docs/yaml-reference/assets/index.md, content/docs/yaml-reference/compliance/index.md, content/docs/yaml-reference/estate-info/index.md, content/docs/yaml-reference/events/index.md, content/docs/yaml-reference/locations/index.md, content/docs/yaml-reference/story-runner-components/index.md, content/docs/yaml-reference/subjects/index.md
Notes on YAML Runner set up changed from jitsuin-archivist to rkvst-archivist.
=> Change to rkvst-archivist package name 

content/docs/api-reference/app-registrations-api/index.md, content/docs/api-reference/assets-api/index.md, content/docs/api-reference/blockchain-api/index.md, content/docs/api-reference/events-api/index.md, content/docs/api-reference/iam-policies-api/index.md, content/docs/api-reference/invites-api/index.md, content/docs/api-reference/locations-api/index.md, content/docs/api-reference/public-assets-api/index.md, content/docs/beyond-the-basics/public-attestation/index.md, content/docs/rkvst-basics/creating-an-asset/index.md, content/docs/rkvst-basics/creating-an-event-against-an-asset/index.md, content/docs/rkvst-basics/managing-access-to-an-asset-with-abac/index.md
Added cross-linking to sections that point to other relevant and/or pre-requisite areas of the documentation.
=> adding cross-linking to sections

content/docs/beyond-the-basics/verifying-with-simple-hash/index.md
Added information about retrieving public asset transaction details and batched commit frequency.
=> Notes on Verifying Simple Hash for Public Assets

content/docs/user-patterns/authenticity-and-attestation/index.md
Revisions to existing user pattern section.
=> Authenticity and Attestation User Pattern Revision

content/docs/user-patterns/bill-of-materials/index.md
Initial Bill of Materials user pattern revision.
=> BOM User Pattern Revision

content/docs/developer-patterns/namespace/index.md
First/rough draft of namespace developer pattern.
=> Namespace Developer Pattern

README.md
Fixed link in README and minor grammatical edits
=> contributing guidelines link fix in README

assets/js/index.js
The search bar didn't work...now it does!
=> Fix search bar

content/platform/overview/introduction/index.md
=> Adding an alias for the introduction page

content/platform/overview/scitt-receipts/index.md
=> Tidy up a bit of receipt messaging

content/platform/administration/dropbox-integration/index.md
=> Correcting recurring typo of DropBox to Dropbox

config/_default/menus.toml, content/usecases/_index.md, content/usecases/bill-of-materials/index.md, layouts/index.html, layouts/partials/header/header.html
I deleted the previous PR for this (where usecases became examples) and moved everything back to "usecases" in the docs structure.
=> Improvements to the home page and header nav bar.

.vscode/settings.json
An optional file for contributors to benefit from common RKVST used words, phrases, UK spelling of words like "behaviour" and common `HUGO` or `doks` terms
=> Save an RKVST dictionary for VS Code spell checking

content/contributing/formatting-content/style-guide/index.md
=> Add ID masking to contributing guidelines

content/glossary/reserved-attributes/index.md, content/platform/overview/advanced-concepts/index.md
=> Minor update to reserved terms glossary

content/glossary/reserved-attributes/index.md, layouts/_default/_markup/render-link.html
Links that point to an external website now open in a new tab
=> Added code to open external links in a new tab

content/developers/api-reference/iam-policies-api/index.md, content/developers/api-reference/tenancies-api/index.md
Add Swagger references that have been split.
=> Fix swagger references

content/developers/developer-patterns/document-profile/index.md, content/developers/developer-patterns/software-package-profile/index.md, content/developers/developer-patterns/verifying-with-simple-hash/index.md, content/usecases/bill-of-materials/index.md
Remaining Developer Pattern docs updated based on the Miro board notes.
=> Part 2 of the Jan 2024 content refresh

content/developers/api-reference/app-registrations-api/index.md, content/developers/api-reference/assets-api/index.md, content/developers/api-reference/attachments-api/index.md, content/developers/api-reference/blobs-api/index.md, content/developers/api-reference/blockchain-api/index.md, content/developers/api-reference/compliance-api/index.md, content/developers/api-reference/events-api/index.md, content/developers/api-reference/iam-policies-api/index.md, content/developers/api-reference/iam-subjects-api/index.md, content/developers/api-reference/invites-api/index.md, content/developers/api-reference/locations-api/index.md, content/developers/api-reference/public-assets-api/index.md, content/developers/api-reference/system-api/index.md, content/developers/api-reference/tenancies-api/index.md, content/developers/api-reference/tls-ca-certificates-api/index.md, content/platform/administration/sharing-access-inside-your-tenant/index.md, content/platform/administration/sharing-access-outside-your-tenant/index.md
Updates to the API reference pages.
Includes some corrections, some improvements and correcting style inconsistencies.
=> API Reference updates

content/platform/overview/advanced-concepts/index.md
This is Kelvin's updated Advanced Concepts page plus some changes I made while reviewing it.
=> Kelvin's updated Advanced Concepts with additional changes

content/developers/developer-patterns/_index.md, content/glossary/common-datatrails-terms/index.md
[AB#9328](https://dev.azure.com/jitsuin/0629f48c-3979-4bbc-9026-cb06b3dfd0ae/_workitems/edit/9328)
=> Remove mentions of simplehash

content/developers/developer-patterns/scitt-api/index.md
A few nits for changes to hashed payloads and other items that are no longer consistent
=> Cleanup of the SCITT Sample

content/developers/developer-patterns/getting-access-tokens-using-app-registrations/index.md, content/developers/developer-patterns/scitt-api/index.md
Also, includes: creating transparent_statement
=> Migrate to register_signed_statement

content/developers/api-reference/events-api/index.md, content/developers/developer-patterns/containers-as-assets/index.md, content/developers/developer-patterns/software-package-profile/index.md, content/developers/yaml-reference/assets/index.md, content/developers/yaml-reference/events/index.md, content/platform/administration/grouping-assets-by-location/index.md, content/platform/overview/creating-an-asset/index.md, content/platform/overview/creating-an-event-against-an-asset/index.md, content/platform/overview/registering-a-document-profile-asset/index.md, content/platform/overview/registering-an-event-against-a-document-profile-asset/index.md
Fixes [AB#9787](https://dev.azure.com/jitsuin/0629f48c-3979-4bbc-9026-cb06b3dfd0ae/_workitems/edit/9787)
=> Update guidance on wait_for_confirmation

content/developers/developer-patterns/veracity/index.md
re [AB#9653](https://dev.azure.com/jitsuin/0629f48c-3979-4bbc-9026-cb06b3dfd0ae/_workitems/edit/9653)
=> fix link in veracity page

content/developers/developer-patterns/veracity/index.md
re [AB#9653](https://dev.azure.com/jitsuin/0629f48c-3979-4bbc-9026-cb06b3dfd0ae/_workitems/edit/9653)
=> command naming consistency update

content/developers/developer-patterns/3rdparty-verification/index.md
=> 898- Content formatting edits

.vscode/settings.json, content/developers/api-reference/assets-api/index.md, content/developers/api-reference/events-api/index.md
Relatively minor cleanup to make Events easier to grok, minimizing unnecessary details, prior to the Event Centric changes.
=> Event and Assets API cleanup

content/developers/templates/vcons/index.md
=> Fix Partner-ID

README.md, config/_default/params.toml, content/_index.md, content/platform/_index.md, content/platform/administration/_index.md, content/platform/administration/sharing-access-inside-your-tenant/index.md, content/platform/overview/advanced-concepts/index.md, content/platform/overview/core-concepts/index.md, content/platform/overview/introduction/index.md, content/usecases/sc-asset-lifecycle/index.md, content/usecases/sc-state-machine/index.md
[AB#10038](https://dev.azure.com/jitsuin/0629f48c-3979-4bbc-9026-cb06b3dfd0ae/_workitems/edit/10038)
=> Modify concepts sections to point at Event-Centric future

layouts/shortcodes/openapi.html
Path before:
get  /archivist/v2/assets/archivist/v2/assets
Path after:
get  /archivist/v2/assets
fixes [AB#10169](https://dev.azure.com/jitsuin/0629f48c-3979-4bbc-9026-cb06b3dfd0ae/_workitems/edit/10169)
=> Remove openapi basepath

content/developers/api-reference/assets-api/index.md, content/developers/api-reference/events-api/index.md, content/developers/api-reference/iam-policies-api/index.md, content/platform/overview/advanced-concepts/index.md, content/platform/overview/creating-an-event-against-an-asset/index.md, content/platform/overview/registering-an-event-against-a-document-profile-asset/index.md
[AB#10053](https://dev.azure.com/jitsuin/0629f48c-3979-4bbc-9026-cb06b3dfd0ae/_workitems/edit/10053)
=> API example tidy-ups ahead of Event Centric move

content/developers/developer-patterns/massif-blob-offset-tables/index.md
[AB#10448](https://dev.azure.com/jitsuin/0629f48c-3979-4bbc-9026-cb06b3dfd0ae/_workitems/edit/10448)
=> Fix leaf count to a power of 2

content/developers/templates/scitt/index.md, content/developers/templates/vcons/index.md
Pending merge of: https://github.com/vcon-dev/vcon-server/pull/25
=> Updates for 0.3.0
