config/_default/menus.toml, content/docs/api-reference/_index.md, content/docs/api-reference/assets-api/index.md, content/docs/api-reference/attachments-api/index.md, content/docs/api-reference/blobs-api/index.md, content/docs/api-reference/blockchain-api/index.md, content/docs/api-reference/compliance-api/index.md, content/docs/api-reference/events-api/index.md, content/docs/api-reference/groups-api/index.md, content/docs/api-reference/iam-policies-api/index.md, content/docs/api-reference/locations-api/index.md, content/docs/api-reference/microsoft-iothub-api/index.md, content/docs/api-reference/svc-buses-api/index.md, content/docs/api-reference/system-api/index.md, content/docs/api-reference/tenancies-api/index.md, content/docs/api-reference/tls-ca-certificates-api/index.md, layouts/shortcodes/openapi.html
Adding the underlying references to the OpenAPI docs which should then pull in info from our existing docs automatically
Also fixing an issue in how whole accordion items were being labelled with similar tags so that when multiple were on a page they would end up interacting with eachother
Now I strip " API" from the title of the document and then insert that in as an identifier to make each accordion unique - this does cause an issue with the System API document but that does not follow the conventional title (it has a space between "Archivist Node") and should be amended like the other swagger files to "ArchivistNode" (see "MicrosoftIoTHub")
I also fixed an errant `</div>` which was causing layout issues with other components
=> Commiting API Docs + Fix for OpenAPI shortcode

content/contributing/playground/openapi-example-render/index.md, layouts/shortcodes/openapi.html
There was an issue that with some of the newer openapi specs that longer endpoints would be poorly rendered and spill over
This fixes the behaviour by creating overflow divs around the button text and the title, the button text becomes unscrollable but no longer overspills, when you expand the title you then have the full one which scrolls
=> Fixing overflowing endpoints when text is too long

content/contributing/playground/openapi-example-render/index.md, content/docs/api-reference/attachments-api/index.md, content/docs/api-reference/blobs-api/index.md, content/docs/api-reference/blockchain-api/index.md, content/docs/api-reference/compliance-api/index.md, content/docs/api-reference/iam-policies-api/index.md, content/docs/api-reference/iam-subjects-api/index.md, content/docs/api-reference/svc-buses-api/index.md, content/docs/api-reference/system-api/index.md, content/docs/api-reference/tenancies-api/index.md, content/docs/api-reference/tls-ca-certificates-api/index.md
Prep for new swaggers being pushed
All references should have a {{endpoint}}{{version}}.swagger.json format
This is expected to fail until the new swaggers are made available
=> Updated swagger references

layouts/shortcodes/openapi.html
Engineering have begun tagging paths they need declared in swaggers for internal mechanisms but don't want documented with an "Unsupported" tag - this PR allows for filtering methods based on if "Unsupported" is (not) in the tags
=> Adding support for "Unsupported" to hide methods

layouts/shortcodes/tabs.html
Writing non-codelang text in tabs would not render correctly; this puts hugo's smart-ish mardownifying filter in front to catch text that needs to render correctly
=> Markdownify fix for poorly rendered tabs content

content/docs/api-reference/assets-api/index.md, content/docs/api-reference/public-assets-api/index.md, content/docs/api-reference/tenancies-api/index.md, content/docs/api-reference/tls-ca-certificates-api/index.md
Added most of the explaining sections which need a review, also need someone from Engineering to update the following curl examples
In Assets API:
* Fetching a Public Asset's URL
* Fetching a Public Asset's Event URL
In Public Assets API
* Fetch a Public Asset Record
* Fetch all of a Public Asset's Events Records
* Fetch a Public Asset's specific Event Record
=> Adding Public Assets to API Reference

content/docs/api-reference/app-registrations-api/index.md, content/docs/api-reference/iam-policies-api/index.md
Specifying types of policies and their respective user identifiers. Phrasing may need reworking and examples might be needed.
=> Adding note about ABAC vs OBAC to API docs

content/docs/api-reference/compliance-api/index.md, content/docs/overview/advanced-concepts/index.md
Changing incorrect 'arc_correlation_id' to correct 'arc_correlation_value' in Advanced Concepts section.
=> arc_correlation_id to arc_correlation_value

content/docs/api-reference/assets-api/index.md, content/docs/api-reference/compliance-api/index.md, content/docs/api-reference/iam-policies-api/index.md, content/docs/api-reference/iam-subjects-api/index.md, content/docs/api-reference/locations-api/index.md, content/docs/api-reference/tls-ca-certificates-api/index.md
Quotes added around URLs with queries so bash doesn't misinterpret the URL when curl commands are used. Otherwise, '?' within string gets misinterpreted and the error 'zsh: no matches found' is displayed.
=> Adding Quotes Around URLs with Query Strings

content/docs/api-reference/iam-policies-api/index.md, content/docs/rkvst-basics/getting-access-tokens-using-app-registrations/index.md, content/docs/rkvst-basics/managing-access-to-an-asset-with-abac/index.md
Added instructions for using the 'jwt_' prefix to match on a json web token claim when granting permissions using ABAC.
=> adding jwt claim info to ABAC

layouts/partials/head/head.html
The earlier fix worked for local builds but GitHub Pages doesn't accept HTTP header configuration so we need to put it in the HTML instead.
=> Add CSP headers for GitHub Pages prod

content/developers/developer-patterns/getting-access-tokens-using-app-registrations/index.md
=> Adding an alias for access tokens that was outside the api reference

content/developers/api-reference/assets-api/index.md, content/developers/api-reference/events-api/index.md
Added Document Profile examples to the Assets and Events API reference articles.
=> Document Profile examples in API references.

content/developers/api-reference/app-registrations-api/index.md, content/developers/api-reference/assets-api/index.md, content/developers/api-reference/attachments-api/index.md, content/developers/api-reference/blobs-api/index.md, content/developers/api-reference/blockchain-api/index.md, content/developers/api-reference/compliance-api/index.md, content/developers/api-reference/events-api/index.md, content/developers/api-reference/iam-policies-api/index.md, content/developers/api-reference/iam-subjects-api/index.md, content/developers/api-reference/invites-api/index.md, content/developers/api-reference/locations-api/index.md, content/developers/api-reference/public-assets-api/index.md, content/developers/api-reference/system-api/index.md, content/developers/api-reference/tenancies-api/index.md, content/developers/api-reference/tls-ca-certificates-api/index.md
Added a friendly note to the top of each API reference page. The intention is to make clearer that these pages are for experienced developers and suggest that there are better options for kicking the tyres of the API
=> API reference intended audience note

content/platform/administration/dropbox-integration/index.md
Update to the Dropbox Integration article. Changed to connect/select/linked wording and added a section on updating the linked folder list as requested by the UX team.
=> Dropbox Integration updates

assets/scss/common/_dark.scss, assets/scss/common/_global.scss, assets/scss/common/_variables.scss, layouts/index.html
stylesheet changes to improve the homepage and fix dark mode for the navigation cards and search function
This was reporting a warning about backwards compatibility:
// https://fossheim.io/writing/posts/css-text-gradient/
.gradient-text {
background-color: $primary;
background-image: linear-gradient(90deg, $rkvst-blue, $rkvst-blue 50%, $rkvst-blue);
background-size: 100%;
background-repeat: repeat;
-webkit-background-clip: text;
-moz-background-clip: text;
-webkit-text-fill-color: transparent;
-moz-text-fill-color: transparent;
}
I did what it suggested and added:
background-clip: text;
Nothing seemed to break so I left it in the PR but it isn't really part of it.
<sub><img src="https://user-images.githubusercontent.com/4775299/87437657-e7332b00-c5ee-11ea-958d-589dfb19d72c.png" alt=" " …
=> dark mode fixes to the search function and navigation cards

content/developers/developer-patterns/scitt-api/index.md
~~Adds a script from [datatrails-scitt-samples](https://github.com/datatrails/datatrails-scitt-samples/) to aide in waiting for the ledger to anchor the transparent statement~~
~~Dependent upon: https://github.com/datatrails/datatrails-scitt-samples/pull/4~~
Includes other cleanup items as well for bash, vs. shell providing better color viewing in the docs, and cleanup of mediatypes, and todo links
=> SCITT API Cleanup

archetypes/archive.md, config/_default/menus.toml, content/archive/_index.md, content/archive/scitt-receipts/index.md, layouts/archive/list.html, layouts/archive/single.html, layouts/partials/main/archive-navigation.html, layouts/partials/sidebar/archive-menu.html, layouts/partials/sidebar/archive-toc.html
I created a new Archive section with it's own side menu.
I moved the DataTrails SCITT receipt article into it.
=> Archive the DataTrails SCITT receipt article.

content/archive/_index.md, content/archive/verify-receipts/index.md, content/contributing/_index.md, content/contributing/adding-content/_index.md, content/contributing/adding-content/adding-articles-to-datatrails-docs/index.md, content/contributing/adding-content/adding-content-sections-to-datatrails-docs/index.md, content/contributing/adding-content/creating-your-branch/index.md, content/contributing/formatting-content/_index.md, content/contributing/formatting-content/advanced-formatting/index.md, content/contributing/formatting-content/basic-markdown-formatting/index.md, content/contributing/formatting-content/style-guide/index.md, content/contributing/getting-started/_index.md, content/contributing/getting-started/pulling-and-building-rkvst-docs/index.md, content/contributing/playground/openapi-example-render/index.md, content/contributing/playground/test-page/index.md, content/sales/_index.md, content/sales/contactus/index.md, content/support/_index.md, content/support/contactus/index.md, layouts/robots.txt
robots.txt has been modified to allow the use of an article setting 
`robotsdisallow: true`
The effect of this is to add the page to robots.txt
I found another one in sitemap.xml
`sitemap_exclude: true`
The effect of this is to exclude the page from sitemap.xml
Both of these are needed to stop pages being indexed by a search engine.
These hidden or obsolete sections are now excluded using this method:
archive
contributing
sales
support
=> add setting to be added to article frontmatter to block web crawlers

layouts/shortcodes/openapi.html
Update openapi generator to support the new swagger paths where we now use basepath correctly
fixes [AB#9069](https://dev.azure.com/jitsuin/0629f48c-3979-4bbc-9026-cb06b3dfd0ae/_workitems/edit/9069)
=> 9069-support-basepath

content/developers/developer-patterns/scitt-api/index.md
@beekman33 noticed the url for the events API didn't work on a mac. Enclosing with quotes worked. 
We also added a generic link to the python dependency.
=> Add python pre-req and quotes for mac curl

content/developers/api-reference/assets-api/index.md, content/developers/api-reference/events-api/index.md, content/developers/api-reference/iam-policies-api/index.md, content/developers/api-reference/public-assets-api/index.md, content/developers/developer-patterns/containers-as-assets/index.md, content/developers/developer-patterns/getting-access-tokens-using-app-registrations/index.md, content/developers/developer-patterns/software-package-profile/index.md, content/developers/developer-patterns/verifying-with-simple-hash/index.md, content/developers/yaml-reference/assets/index.md, content/developers/yaml-reference/events/index.md, content/developers/yaml-reference/subjects/index.md, content/platform/overview/advanced-concepts/index.md, content/platform/overview/creating-an-asset/index.md, content/platform/overview/registering-a-document-profile-asset/index.md
The API examples have been updated to:
change CONFIRMED to COMMITTED
remove the SIMPLE_HASH proof mechanism
remove arc_firmware_version and some examples of arc_home_location_identity
SIMPLE HASH has been de-emphasized in the docs.
=> Updates to replace CONFIRMED with COMMITED and remove SIMPLE HASH 

content/developers/api-reference/assets-api/index.md, content/developers/api-reference/events-api/index.md
Added a JSON example for updating an Asset attribute value to the Assets and Events API reference pages.
=> API REF: how to update an Asset attribute

content/developers/developer-patterns/veracity/index.md
This PR adds user-friendly (hopefully!) documentation for the `verify-inclusion` and `node` commands of the Veracity tool. Looking for feedback on the accuracy (@robinbryce) and also the messaging, clarity and tone (@JAG-UK )
Layout example:
re [AB#9653](https://dev.azure.com/jitsuin/0629f48c-3979-4bbc-9026-cb06b3dfd0ae/_workitems/edit/9653)
=> Add Veracity Docs to Developer Patterns

content/developers/api-reference/members-api/index.md
Explains the role stripping behavior when deactivating a user, and how to remediate this after re-activation.
re [AB#10036](https://dev.azure.com/jitsuin/0629f48c-3979-4bbc-9026-cb06b3dfd0ae/_workitems/edit/10036)
=> add note on role stripping behaviour

content/developers/developer-patterns/scitt-api/index.md
* remove use of /tmp in favour of current working directory. tmp breaks the examples for macos
* note that indexing and retrieval for the meta map is a future release thing.
* describe how to capture the leaf hash from registration so verification can be accomplished directly
* purposefuly don't get into the details of computing the leaf hash
* remove use of `${SCRIPTS}` in favour of `python -m` which works on all platforms
=> feat: updates for cbor all the things

.github/workflows/deploy-github.yml, .github/workflows/test-build.yml
Change actions runner image from deprecated Ubuntu 20.04 to ubuntu-latest
Test evidence - this PR build passes
Fixes [AB#10623](https://dev.azure.com/jitsuin/0629f48c-3979-4bbc-9026-cb06b3dfd0ae/_workitems/edit/10623)
=> update actions runner to ubuntu-latest

content/developers/api-reference/asset-events-api/index.md, content/developers/api-reference/assets-api/index.md, content/developers/api-reference/attachments-api/index.md, content/developers/api-reference/blobs-api/index.md, content/developers/api-reference/events-api/index.md, content/glossary/reserved-attributes/index.md, content/platform/overview/advanced-concepts/index.md
Updates attachments for Asset-Events and Events
A small bit of refactoring moving the Primary Image details from Attachments to Asset-Event and Events
~This PR currently contains a section for `arc_`, which I'll likely move to a separate holistic PR.~
=> Attachment Updates

content/developers/api-reference/events-api/index.md
Update docs with new event repsponse shape
[AB#10264](https://dev.azure.com/jitsuin/0629f48c-3979-4bbc-9026-cb06b3dfd0ae/_workitems/edit/10264)
=> Update docs with new event repsponse shape

content/developers/api-reference/events-api/index.md
Fixes for events docs
[AB#10264](https://dev.azure.com/jitsuin/0629f48c-3979-4bbc-9026-cb06b3dfd0ae/_workitems/edit/10264)
=> Fixes for events docs
